### ISSUE TITLE
to-do border

### ISSUE THREAD

**Issue by shirameirovitz** [eyalzimerman/pre-course-2021-final-boilerplate#2]
When adding task with a long text in it: the text, checkbox and delete button continues inline and goes out the border.

Step to reproduce:

Add task with a long text
Exepted Result:
to-do will stay in border (down a line...)

Actual Result:
Showing a long inline task

**Comment by eyalzimerman** [comment]
hey @shirameirovitz ,
i fixed this bug. thank you for notice me.
Enjoy!

**Comment by listguy** [comment]
👌👌
